@startuml
title Asynchronous I/O model
hide footbox
skinparam monochrome true
skinparam defaultFontName Arial
skinparam titleFontSize 16
skinparam sequenceMessageAlign center
activate application
application->kernel: operation\ninitiation
activate kernel
Note right of kernel: wait for data
Note right of kernel: copy data
kernel-->application: completion\ncallback
deactivate kernel
||15||
@enduml
