@startuml
title asynchronous I/O model
hide footbox
skinparam monochrome true
skinparam shadowing false
activate Application
Application->>Kernel: system call
activate Kernel
Kernel-->>Application: return
Note right of Kernel: wait for data
Note right of Kernel: copy data
Kernel-->Application: completion\ncallback
deactivate Kernel
||15||
@enduml
