@startuml
title Blocking I/O model
hide footbox
skinparam monochrome true
skinparam defaultFontName Arial
skinparam titleFontSize 16
skinparam sequenceMessageAlign center
activate application
application->>kernel: reading data
deactivate application
activate kernel
Note right of kernel: wait for data
Note right of kernel: copy data
kernel-->>application: data
deactivate kernel
activate application
||15||
@enduml
