@startuml
title I/O multiplexing model
hide footbox
skinparam monochrome true
skinparam titleFontSize 16
activate application
application->>kernel: system call
activate kernel
Note right of kernel: wait for data\nin many\ndescriptors
kernel-->>application: returned readable
application->>kernel: system call
deactivate application
Note right of kernel: copy data
kernel-->>application: returned data
deactivate kernel
activate application
||15||
@enduml
