@startuml
title I/O multiplexing model
hide footbox
skinparam monochrome true
skinparam defaultFontName Microsoft Sans Serif
skinparam titleFontSize 15

skinparam sequenceMessageAlign center
activate application
application->>kernel: reading\ndescriptor
deactivate application
activate kernel
Note right of kernel: wait for data\nin at least one\ndescriptor
kernel-->>application: available\ndescriptor
deactivate kernel
activate application
application->>kernel: reading data
deactivate application
activate kernel
Note right of kernel: copy data
kernel-->>application: data
deactivate kernel
activate application
||15||
@enduml
