@startuml
title Non-blocking I/O model
hide footbox
skinparam monochrome true
skinparam defaultFontName Microsoft Sans Serif
skinparam titleFontSize 15
skinparam sequenceMessageAlign center
activate application
loop until data is available
    application->>kernel: reading data
    deactivate application
    activate kernel
    alt no data available
        kernel-->>application: error code
    else data  available
        Note right of kernel: copy data
        kernel-->>application: data
        deactivate kernel
        activate application
    end
end
||15||
@enduml
