@startuml
title Non-blocking I/O model
hide footbox
skinparam monochrome true
skinparam titleFontSize 16
activate application
loop wait until data is available
    application->>kernel: system call
    deactivate application
    activate kernel
    Note right of kernel: wait for data
    kernel-->>application: no data available
    deactivate kernel
    activate application
end
application->>kernel: system call
deactivate application
activate kernel
Note right of kernel: copy data
kernel-->>application: returned data
deactivate kernel
activate application
||15||
@enduml
