@startuml
title signal-driven I/O model
hide footbox
skinparam monochrome true
skinparam titleFontSize 16
activate application
application->>kernel: system call
activate kernel
kernel-->>application: return
Note right of kernel: wait for data
kernel-->application: signal
application->>kernel: system call
deactivate application
Note right of kernel: copy data
kernel-->>application: returned data
deactivate kernel
activate application
||15||
@enduml
