@startuml
title Signal-driven I/O model
scale 1.2
hide footbox
skinparam monochrome true
skinparam defaultFontName Microsoft Sans Serif
skinparam titleFontSize 15
skinparam sequenceMessageAlign center
activate application
application->kernel: signal handler\nestablishing
activate kernel
Note right of kernel: wait for data
kernel->application: signal
application->>kernel: reading data
deactivate application
Note right of kernel: copy data
kernel-->>application: data
deactivate kernel
activate application
||10||
kernel -[#white]->]
@enduml
