@startuml
title Signal-driven I/O model
hide footbox
skinparam monochrome true
skinparam defaultFontName Microsoft Sans Serif
skinparam titleFontSize 15
skinparam sequenceMessageAlign center
activate application
application->kernel: establish\nsignal handler
activate kernel
Note right of kernel: wait for data
kernel->application: readiness\nsignal
application->>kernel: reading data
deactivate application
Note right of kernel: copy data
kernel-->>application: data
deactivate kernel
activate application
||4||
kernel -[#white]->]
@enduml
