@startuml
title I/O multiplexing model
hide footbox
skinparam monochrome true
skinparam shadowing false
activate Application
Application->>Kernel: system call
activate Kernel
Note right of Kernel: wait for data\nin many\ndesriptors
Note left of Application: is blocked\nuntil one\nof the descriptors\nis readable
Kernel-->>Application: returned readable
Application->>Kernel: system call
deactivate Application
Note right of Kernel: copy data
Kernel-->>Application: returned data
deactivate Kernel
activate Application
@enduml