@startuml
skinparam monochrome true
skinparam shadowing false
    activate Application
    Application->>Kernel: system call
    activate Kernel
    Kernel-->>Application: return
    Note right of Kernel: wait for data
    Note left of Application: isn't blocked
    deactivate Kernel
    activate Kernel
    Note right of Kernel: copy data
    Kernel--xA: callback
    deactivate Kernel
    deactivate Application
    activate Application
    deactivate Application
@enduml