@startuml
title Asynchronous I/O model
hide footbox
skinparam monochrome true
skinparam shadowing false
activate Application
Application->>Kernel: system call
activate Kernel
Kernel-->>Application: return
Note right of Kernel: wait for data
Note left of Application: isn't blocked
Note right of Kernel: copy data
Kernel-->Application: callback
deactivate Kernel
deactivate Application
@enduml